services:
  db:
    image: mysql:8.0
    container_name: work-order-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbwoit
      MYSQL_USER: adminit2025
      MYSQL_PASSWORD: databaseit2045

    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - workorder-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "adminit2025", "-pdatabaseit2045"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: work-order-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: adminit2025
      DB_PASSWORD: databaseit2045
      DB_NAME: dbwoit
      TIME_TRACKER_URL: "http://time-tracker:9000"
    expose:
      - "8080"
    networks:
      - workorder-net

  nginx:
    image: nginx:1.25-alpine
    container_name: work-order-nginx
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
      - ./login.html:/usr/share/nginx/html/login.html
      - ./summary.html:/usr/share/nginx/html/summary.html
      - ./kaizen.html:/usr/share/nginx/html/kaizen.html
      - ./techguide.html:/usr/share/nginx/html/techguide.html
      - ./static:/usr/share/nginx/html/static
    networks:
      - workorder-net

volumes:
  db_data:

networks:
  workorder-net:
    driver: bridge
